---
title: "Introduction of Joe Sartini"
description: |
  This is a website to help get to know Joe Sartini for Biostat 776.
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

```

## About Me

### Background
I am a first year PhD student in the Biostatistics department, and I am freshly graduated with my undergraduate degree from the Operations Research and Financial Engineering department at Princeton University. Through coursework in my previous program and various research and industry internships, I have experience in machine learning, particularly linear models and deep neural networks, stochastic optimization, and software engineering.

### Research Interests
I currently have a loose interest in the use of EHR data within stochastic models to improve and implement precision medicine. However, I am honestly open to any health science applications which involve the use of machine learning or other models to form actionable insights in the world of healthcare using the wealth of health and personal data made possible by the digital age. 

### Relevant Experience
For my most related experience, I have used R in several courses to implement data-based models, such as linear models, SVMs, and neural networks, to facilitate solving of problems related primarily to finance or forecasting. More generally, I have been a broad programming background acquired over the course of my academic and industry experiences. This background ranges from distributed computation in Scala/Spark to Monte Carlo Simulation, to deep learning models for computer vision in the context of self-driving cars.

### Learning Goals
In this class, I look forward most to learning how to more seamlessly produce appealing statistical reports which convey results such that they are both easy to understand and replicate.


